### ISSUE TITLE
Admin user already set in database?

### ISSUE THREAD

**Issue by jshimko** [dunkelstern/ghost-theme-development#1]
First, thanks for sharing this!  It's exactly the what I was looking for to automate theme development.

I'm noticing that the dev database was committed to the repo here and it appears to already have the default admin user set.  I can't create an account at `http://localhost:2368/ghost/signup/` and when I delete the database, I get a terminal full of errors when I restart ghost (even though Ghost creates a new db in its place).  I've tried a variety of things to get a fresh Ghost instance going with this repo and nothing seems to do the trick.  Any suggestions on what I might be missing?

**Comment by jshimko** [comment]
Nevermind.  It looks like I sorted it out.  Running `npm update` after the initial install did the trick.  I guess an outdated package was screwing things up.  I can now delete the db and Ghost will create a new one and run migrations.

Thanks!

**Comment by dunkelstern** [comment]
Database was included to kickstart development (current theme setting is in the db)

**Comment by jshimko** [comment]
But then anyone that clones this repo doesn't have access to the backend without your account credentials.  :) 

I ended up adding Casper as a submodule to avoid the missing theme errors when starting with a fresh database and to have a reference theme for development.  Then I gitignore'd the database to avoid the above issue.  Now a fresh clone of the repo has first-user access and you just have to select the custom theme in the backend.

I'm in the process of customizing this project to my preferences and adding things like bower integration, a deploy task, and private configs.  I'll share it when I get to a stable spot.

Thanks again for sharing this.  It was a huge time saver!
